export * from './event.service'
export * from './event.model'
export * from './restricted-words.validator'
export * from './duration.pipe'
export * from './locationValidator.directive'
export * from '../event-details/index'
export * from '../events-list.component'
export * from './events-list-resolver.service'